apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      chart: secrets-store-csi-driver
      targetRevision: 1.6.0
      helm:
        valueFiles:
          - $values/k3s/infra/secrets-store-csi/values.yaml

    - repoURL: https://github.com/manos-grigorakis/homelab.git
      targetRevision: main
      path: k3s/infra/secrets-store-csi
      ref: values
  project: default
