# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

configMapGenerator:
  - name: indexer-conf
    files:
      - indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml
  - name: wazuh-conf
    files:
      - wazuh_managers/wazuh_conf/master.conf
      - wazuh_managers/wazuh_conf/worker.conf
  - name: dashboard-conf
    files:
      - indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml
  - name: wazuh-internal-options
    files:
      - wazuh_managers/wazuh_conf/local_internal_options.conf
  - name: wazuh-custom-rules
    files:
      - wazuh_managers/wazuh_conf/local_rules.xml

resources:
  - base/wazuh-ns.yaml
  - base/storage-class.yaml

  # Self signed certs with Cert-Manager
  - certs/wazuh-selfsigned.yaml
  - certs/dashboard_http/dashboard-selfsigned-certificate.yaml
  - certs/indexer_cluster/indexer-selfsigned-certificate.yaml
  - certs/filebeat/filebeat-selfsigned-certificate.yaml

  - secrets/vault-secrets.yaml

  - wazuh_managers/wazuh-cluster-svc.yaml
  - wazuh_managers/wazuh-master-svc.yaml
  - wazuh_managers/wazuh-workers-svc.yaml
  - wazuh_managers/wazuh-master-sts.yaml
  - wazuh_managers/wazuh-worker-sts.yaml

  - indexer_stack/wazuh-indexer/indexer-svc.yaml
  - indexer_stack/wazuh-indexer/cluster/indexer-api-svc.yaml
  - indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

  - indexer_stack/wazuh-dashboard/dashboard-svc.yaml
  - indexer_stack/wazuh-dashboard/dashboard-deploy.yaml

  - ism-policies/configmap-policy.yaml
  - ism-policies/job-apply-retention-policy.yaml

  - templates/configmap-template.yaml
  - templates/job-apply-template.yaml
