apiVersion: v1
kind: ServiceAccount
metadata:
  name: pve-exporter-service-account
  namespace: monitoring

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: pve-exporter-vault-auth
  namespace: monitoring
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pve-exporter-role
    serviceAccount: pve-exporter-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pve-exporter-secret
  namespace: monitoring
spec:
  vaultAuthRef: pve-exporter-vault-auth
  mount: secret
  type: kv-v2
  path: apps/pve-exporter
  refreshAfter: 1m
  destination:
    create: true
    name: pve-exporter-secret
