apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: frigate-vault-auth
  namespace: frigate
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: frigate-role
    serviceAccount: default

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: frigate-secret
  namespace: frigate
spec:
  vaultAuthRef: frigate-vault-auth
  mount: secret
  type: kv-v2
  path: apps/frigate
  refreshAfter: 30s
  destination:
    create: true
    name: frigate-secret
