- name: Setup K3s Main Server
  hosts: "{{ target | default('tags_master') }}"
  vars_files:
    - ../../inventory/group_vars/k3s_cluster.yaml

  tasks:
    - name: Download K3s Install Script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"

    - name: Install K3s
      ansible.builtin.command: /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s # Check if K3s is already present in the machine
      become: true
      environment:
        INSTALL_K3S_EXEC: "server"
        K3S_TOKEN: "{{ cluster_token }}"
      no_log: true

    - name: Wait for K3s Status
      ansible.builtin.pause:
        prompt: "Waiting for K3s to become ready"
        seconds: 30

    - name: Verify K3s Installation
      ansible.builtin.command:
        cmd: kubectl get nodes
      register: k3s_nodes
      become: true
      changed_when: false

    - name: Print K3s Nodes
      ansible.builtin.debug:
        var: k3s_nodes.stdout_lines
