apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  source:
    path: k3s/apps/databases/mysql
    repoURL: https://github.com/manos-grigorakis/homelab.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
