apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  source:
    path: k3s/apps/media/plex
    repoURL: https://github.com/manos-grigorakis/homelab.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
