---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBsP9iYBa2Mcl9DbMTZTho/sGdFBM28LaLv4KW+WsJU7SfJCkKC0qR9LMdguq3o8ksUUU2o3P0zsG9cdmE134oCJ0eUaAEcNUoiS329Szl6Xmy5GLw1Fp7440cqFKI4KdfIa8FRdiHqHf8kZs1P+tKHI+MZBgyfIkCB0yhUWy3ch7P1r0FRZ8HqCEhUKyKjL2y8vU9PRMFQYfwSqEltWhB/O5CjUxqTPoKZGoSRpfq1zTjkLQZ+Tm+ZV9PLDiFyZ78hIe0zRbGWpUM+uRR28ZR9BappDPHN4sVFZy1C7yQRp8Lx22lD4tagGtou9ifH0qTPc+/R1QCZemKytf0YIyy/c+moVxEEOCfUDkRzZS3fOSZ+vdQ0T91eaNYLKrSclOy1p8Nftar75rSOlvgPyGxAE94usM4yJkxmwJe7wJVoYo8yCEB/YcSnWFn5bpWSP5ifI8XXWPNqVyMenV8a7SvxhbahzBxdNKm8JgScpWSrXG2b4Go9yeMfzmkmVd7dny2M6cjo6D7ATKRao299XWZPx6jMxzyPAVGHPDRj5n4LDRIMvMQCNeLaXhsIZC64zu/s3/ShIrSWMPQGyffEbOm7PPzHrxO2BfAklCq5gA9ZvP5mvzGGkkQ06pFR0o+s4R5yFfCWRgSkJ4wR2lvq8Jwf3YMpS4EPWbgfTLtpWElvQvg2tNajM5rpOk0XgKx9OP4Eb9soSOVdOKHUDpRAeuKLHT+Y5iCvnfFfcGG717unFOJns/z86giy27OLwaSrl18glCAfvrDWFKMlRwMgsmwBoL/oCwiH3r0sFjfjD0oJ
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
