apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: immich-secret-provider-class
  namespace: immich
spec:
  provider: vault
  secretObjects:
    - data:
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
      secretName: immich-secret
      type: Opaque
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "immich-role"
    objects: |
      - objectName: "DB_PASSWORD"
        secretPath: "secret/data/apps/immich"
        secretKey: "DB_PASSWORD"
