apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: "lscr.io/linuxserver/bazarr:amd64-1.5.6"
          ports:
            - containerPort: 6767
          envFrom:
            - configMapRef:
                name: media-env
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
