apiVersion: v1
kind: ServiceAccount
metadata:
  name: wazuh-service-account
  namespace: wazuh

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: wazuh-vault-auth
  namespace: wazuh
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: wazuh-role
    serviceAccount: wazuh-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dashboard-cred
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/dashboard
  refreshAfter: 1h
  destination:
    create: true
    name: dashboard-cred

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/indexer
  refreshAfter: 1h
  destination:
    create: true
    name: indexer-cred

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/api
  refreshAfter: 1h
  destination:
    create: true
    name: wazuh-api-cred

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/authd-pass
  refreshAfter: 1h
  destination:
    create: true
    name: wazuh-authd-pass

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/cluster-key
  refreshAfter: 1h
  destination:
    create: true
    name: wazuh-cluster-key

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: internal-users
  namespace: wazuh
spec:
  vaultAuthRef: wazuh-vault-auth
  mount: secret
  type: kv-v2
  path: apps/wazuh/internal-users
  refreshAfter: 1h
  destination:
    create: true
    name: internal-users
