apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd-vault-auth
  namespace: argocd
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: argocd-role
    serviceAccount: argocd-server

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  vaultAuthRef: argocd-vault-auth
  mount: secret
  type: kv-v2
  path: infra/argocd/oidc
  refreshAfter: 5m
  destination:
    create: true
    name: argocd-oidc-secret
    labels:
      app.kubernetes.io/part-of: argocd

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-github-repo-secret
  namespace: argocd
spec:
  vaultAuthRef: argocd-vault-auth
  mount: secret
  type: kv-v2
  path: infra/argocd/github-repo
  refreshAfter: 8h
  destination:
    create: true
    name: github-repo
    labels:
      argocd.argoproj.io/secret-type: repository
