apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/manos-grigorakis/homelab.git
      targetRevision: main
      path: k3s/infra/rbac
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
