apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/manos-grigorakis/homelab.git
      targetRevision: main
      path: k3s/infra/traefik
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=false
