apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-service-account
  namespace: databases

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: postgres-vault-auth
  namespace: databases
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: postgres-role
    serviceAccount: postgres-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  namespace: databases
spec:
  vaultAuthRef: postgres-vault-auth
  mount: secret
  type: kv-v2
  path: apps/databases/postgres
  refreshAfter: 60s
  destination:
    create: true
    name: postgres-secret
