apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: main-dashboard
    options:
      labels:
        grafana_dashboard: "my_custom_dashboards"
    files:
      - grafana/dashboards/main-dashboard.json

  - name: kubernetes-dashboard
    options:
      labels:
        grafana_dashboard: "my_custom_dashboards"
    files:
      - grafana/dashboards/kubernetes-dashboard.json

  - name: loki-dashboard
    options:
      labels:
        grafana_dashboard: "my_custom_dashboards"
    files:
      - grafana/dashboards/loki-dashboard.json

  - name: ups-dashboard
    options:
      labels:
        grafana_dashboard: "my_custom_dashboards"
    files:
      - grafana/dashboards/ups-dashboard.json

  - name: logistics-platform-dashboard
    options:
      labels:
        grafana_dashboard: "my_custom_dashboards"
    files:
      - grafana/dashboards/logistics-platform-dashboard.json

  # Datasources
  - name: loki-datasource
    options:
      labels:
        grafana_datasource: "my_custom_datasources"
    files:
      - grafana/datasources/loki.yaml

resources:
  # Secrets
  - pve-exporter/vault-secrets.yaml
  - grafana/vault-secrets.yaml
  - alert-manager/vault-secrets.yaml

  # Services
  - pve-exporter/service.yaml
  - pve-exporter/service-monitor.yaml
  - nut-exporter/service.yaml

  # Ingress Routes
  - alert-manager/alertmanager-ingress-route.yaml
  - grafana/grafana-ingress-route.yaml
  - prometheus/prometheus-ingress-route.yaml

  # Deployments
  - pve-exporter/deploy.yaml
  - nut-exporter/deploy.yaml

  # Other (CRDs...)
  - pve-exporter/scrape-config.yaml
  - nut-exporter/bitmore-scrape-config.yaml
  - nut-exporter/cyberpower-rack-scrape-config.yaml
  - prometheus/scrape-configs/logistics-platform-scape-config.yaml

  # Rules
  - prometheus/rules/cpu-memory.rules.yaml
  - prometheus/rules/disk-storage.rules.yaml
  - prometheus/rules/node.rules.yaml
