apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb-service
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      serviceAccountName: mariadb-service-account
      containers:
        - name: mariadb
          image: "mariadb:11.8"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "mariadb-secret-provider-class"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Gi
