apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-service-account
  namespace: databases

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mariadb-vault-auth
  namespace: databases
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: mariadb-role
    serviceAccount: mariadb-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-secret
  namespace: databases
spec:
  vaultAuthRef: mariadb-vault-auth
  mount: secret
  type: kv-v2
  path: apps/databases/mariadb
  refreshAfter: 60s
  destination:
    create: true
    name: mariadb-secret
