apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: logistics-platform
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobName: "logistics_platform"
  staticConfigs:
    - targets: ["192.168.10.56:30090"]
  metricsPath: /actuator/prometheus
  scheme: HTTP
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: instance
