apiVersion: v1
kind: ServiceAccount
metadata:
  name: filament-tracker-service-account
  namespace: filament-tracker

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: filament-tracker-vault-auth
  namespace: filament-tracker
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: filament-tracker-role
    serviceAccount: filament-tracker-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: filament-tracker-secret
  namespace: filament-tracker
spec:
  vaultAuthRef: filament-tracker-vault-auth
  mount: secret
  type: kv-v2
  path: apps/filament-tracker
  refreshAfter: 60s
  destination:
    create: true
    name: filament-tracker-secret
