apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poolnode-wildcard
  namespace: cert-manager
spec:
  secretName: poolnode-wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns01
  dnsNames:
    - "poolnode.net"
    - "*.poolnode.net"
    - "*.k3s.poolnode.net"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"

      # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

      # Empty to apply for all namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
