apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-service-account
  namespace: databases

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: mysql-vault-auth
  namespace: databases
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: mysql-role
    serviceAccount: mysql-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mysql-secret
  namespace: databases
spec:
  vaultAuthRef: mysql-vault-auth
  mount: secret
  type: kv-v2
  path: apps/databases/mysql
  refreshAfter: 60s
  destination:
    create: true
    name: mysql-secret
