apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.poolnode.net
  oidc.config: |
    name: Authentik
    issuer: https://authentik.poolnode.net/application/o/argo-cd/
    clientID: EjYMHoT4u9UDhGpfnwpQsA0k4idmXmK7k6NaV9Hj

    # Reference key in argocd-secret
    clientSecret: $argocd-oidc-secret:oidc.authentik.clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
