apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../base
  - github-repo-secret.yaml
  - ingress-route.yaml
  - argocd-secret.sealed.yaml
  - oci-registry-ghcr-secret.sealed.yaml

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true # Fix redirection error with Ingress

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
