- name: Disable Unused Kernel Modules
  ansible.builtin.blockinfile:
    path: /etc/modprobe.d/hardening.conf
    create: true
    prepend_newline: true
    owner: root
    group: root
    mode: "0644"
    block: |
      install cramfs /bin/false
      install freevxfs /bin/false
      install hfs /bin/false
      install hfsplus /bin/false
      install jffs2 /bin/false
      install udf /bin/false

- name: Blacklist Unused Kernel Modules
  ansible.builtin.blockinfile:
    path: /etc/modprobe.d/hardening-blacklist.conf
    create: true
    prepend_newline: true
    owner: root
    group: root
    mode: "0644"
    block: |
      blacklist cramfs
      blacklist hfs
      blacklist hfsplus
      blacklist jffs2
      blacklist udf
