- name: Add sysctl hardening config
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/99-hardening.conf
    create: true
    mode: "0644"
    block: |
      # Enable Suspicious Packets Logging
      net.ipv4.conf.default.log_martians = 1
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.route.flush = 1
  register: sysctl_config

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  when: sysctl_config.changed
  changed_when: true
