- name: Clone GitHub Repository
  hosts: "{{ target | default('k3s_api') }}"

  tasks:
    - name: Clone GitHub Repository
      ansible.builtin.git:
        repo: "https://github.com/manos-grigorakis/homelab.git"
        dest: /home/manos/homelab
        version: "main"
