apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dns

resources:
  - namespace.yaml

  - service-account.yaml
  - secret-provider-class.yaml

  - pihole-configmap.yaml
  - unbound-configmap.yaml

  - pvc.yaml

  - deployment.yaml
  - service.yaml
  - pihole-ui-service.yaml
  - middleware.yaml
  - ingress-route.yaml
