apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-service-account
  namespace: dns

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: dns-vault-auth
  namespace: dns
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: dns-role
    serviceAccount: dns-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dns-secret
  namespace: dns
spec:
  vaultAuthRef: dns-vault-auth
  mount: secret
  type: kv-v2
  path: apps/pi-hole
  refreshAfter: 60s
  destination:
    create: true
    name: dns-secret
