name: Ansible Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ansible/**"

permissions:
  contents: read

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.6.0
        with:
          args: "-v"
          working_directory: "ansible"
          requirements_file: "requirements.yaml"
