apiVersion: v1
kind: ServiceAccount
metadata:
  name: plex-service-account
  namespace: media

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: plex-vault-auth
  namespace: media
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: plex-role
    serviceAccount: plex-service-account

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: plex-secret
  namespace: media
spec:
  vaultAuthRef: plex-vault-auth
  mount: secret
  type: kv-v2
  path: apps/plex
  refreshAfter: 60s
  destination:
    create: true
    name: plex-secret
